version: '3.8'
services:

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend/clientes
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - frontend-build:/app/build
    networks:
      - Clientes
    depends_on:
      - backend

  backend:
    container_name: "backend"
    build:
      context: ./backend/Clientes
      dockerfile: ./Dockerfile
    ports:
      - 8089:8089
    environment:
      - ConnectionStrings__SqlServerConn=${DefaultConnection}
      - MongoDbSettings__MongoDbConn=${MongoDbConn}
      - MongoDbSettings__DatabaseName=${DatabaseName}
      - ASPNETCORE_ENVIRONMENT=${Environment}
      - ASPNETCORE_HTTP_PORTS=${PORT}
    depends_on:
      - db
      - mongodb
    networks:
      - Clientes
    volumes:
      - keys:/root/.aspnet/DataProtection-Keys
      
  db:
    container_name: "db"
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "8001:1433"
    volumes:
      - db:/var/opt/mssql
      - ./configure-remote-access.sql:/docker-entrypoint-initdb.d/configure-remote-access.sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "${PassDBA}"
    networks:
      - Clientes

  mongodb:
    container_name: "mongodb"
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - Clientes
      
volumes:
  keys:
  mongodb_data:
  frontend-build:

  db:
    name: db
    external: false
    
networks:
  Clientes:
    name: Clientes
    driver: bridge